// frontend/src/components/TensorCreator.vue
<template>
  <div class="creator">
    <h2>Create Tensor</h2>
    <select v-model="selectedOp">
      <option value="ones">Ones</option>
      <option value="zeros">Zeros</option>
    </select>
    <input v-model="shapeInput" placeholder="shape (comma-separated)" />
    <button @click="create">Create</button>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useTensorStore } from '../stores/tensorStore';

const store = useTensorStore();
const selectedOp = ref('ones');
const shapeInput = ref('3,3');

async function create() {
  const shape = shapeInput.value.split(',').map(Number);
  await store.createTensor(selectedOp.value, shape);
}
</script>

<style scoped>
.creator {
  margin-bottom: 20px;
}
select, input {
  margin-right: 10px;
  padding: 5px;
}
</style>

// frontend/src/components/TensorCreator.jsx
import React, { useState } from 'react'
import { useTensorStore } from '@/stores/tensorStore'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { PlusCircle } from 'lucide-react'

export default function TensorCreator() {
  const createTensor = useTensorStore((s) => s.createTensor)
  const [op, setOp] = useState('ones')
  const [shapeInput, setShapeInput] = useState('3,3')

  async function handleCreate() {
    const shape = shapeInput.split(',').map(Number)
    await createTensor(op, shape)
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">Create Tensor</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="space-y-1">
          <Label>Initializer</Label>
          <Select value={op} onValueChange={setOp}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="ones">Ones</SelectItem>
              <SelectItem value="zeros">Zeros</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-1">
          <Label>Shape (comma-separated)</Label>
          <Input
            value={shapeInput}
            onChange={(e) => setShapeInput(e.target.value)}
            placeholder="e.g. 3,3"
          />
        </div>
        <Button className="w-full" onClick={handleCreate}>
          <PlusCircle className="mr-2 h-4 w-4" />
          Create
        </Button>
      </CardContent>
    </Card>
  )
}
