// frontend/src/App.jsx
import React from 'react'
import { useTensorStore } from '@/stores/tensorStore'
import TensorCreator from '@/components/TensorCreator'
import OperationPanel from '@/components/OperationPanel'
import TensorDisplay from '@/components/TensorDisplay'
import GraphDisplay from '@/components/GraphDisplay'
import HistoryList from '@/components/HistoryList'
import { Separator } from '@/components/ui/separator'
import { FlaskConical } from 'lucide-react'

export default function App() {
  const currentTensor = useTensorStore((s) => s.currentTensor)
  const graphImage = useTensorStore((s) => s.graphImage)

  return (
    <div className="min-h-screen bg-zinc-50">
      {/* Header */}
      <header className="bg-white border-b border-zinc-200 px-6 py-4">
        <div className="max-w-screen-xl mx-auto flex items-center gap-3">
          <FlaskConical className="h-6 w-6 text-zinc-700" />
          <div>
            <h1 className="text-lg font-semibold tracking-tight">PyTorch Tensor Playground</h1>
            <p className="text-xs text-muted-foreground">
              Create a tensor, apply operations step by step, and watch the computation graph update.
            </p>
          </div>
        </div>
      </header>

      {/* Main layout */}
      <main className="max-w-screen-xl mx-auto px-6 py-6">
        <div className="flex gap-6">
          {/* Left panel */}
          <div className="w-72 shrink-0 flex flex-col gap-4">
            <TensorCreator />
            <OperationPanel />
            <HistoryList />
          </div>

          <Separator orientation="vertical" className="self-stretch" />

          {/* Right panel */}
          <div className="flex-1 flex flex-col gap-4">
            <TensorDisplay tensor={currentTensor} title="Current Tensor" />
            <GraphDisplay image={graphImage} />
          </div>
        </div>
      </main>
    </div>
  )
}

// frontend/src/App.vue
<template>
  <div class="app">
    <h1>🔬 PyTorch Tensor Playground</h1>
    <p>Create a tensor, then apply operations step by step. The graph updates after each step.</p>

    <div class="main-panel">
      <div class="left-panel">
        <TensorCreator />
        <OperationPanel />
        <HistoryList />
      </div>
      <div class="right-panel">
        <TensorDisplay :tensor="store.currentTensor" title="Current Tensor" />
        <GraphDisplay :image="store.graphImage" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { useTensorStore } from './stores/tensorStore';
import TensorCreator from './components/TensorCreator.vue';
import OperationPanel from './components/OperationPanel.vue';
import TensorDisplay from './components/TensorDisplay.vue';
import GraphDisplay from './components/GraphDisplay.vue';
import HistoryList from './components/HistoryList.vue';

const store = useTensorStore();
</script>

<style>
/* Global styles */
body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 20px;
  background: #f0f2f5;
}
.app {
  max-width: 1400px;
  margin: 0 auto;
}
.main-panel {
  display: flex;
  gap: 20px;
  margin-top: 20px;
}
.left-panel {
  flex: 1;
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.right-panel {
  flex: 2;
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
</style>
